spring:
  datasource:
    url: "jdbc:h2:file:/data/gym"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    sergio.pruebas.gym.management: DEBUG