version: '3.3'
services:
  postgres:
    ports:
      - '5432:5432'
    volumes:
      - './DB:/var/lib/postgresql/data'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - POSTGRES_PASSWORD=root
    image: 'postgres:15.1'